version: '3.8'

services:
  web:
    image: putrabudiansyah/nginx-php-alpine
    container_name: nginx-php
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
